### ISSUE TITLE
Fan Speed On Ayaneo Next lite

### ISSUE THREAD

**Issue by Ferikash** [playtron-os/playtron-os#159] opened 2024-10-20 14:00 UTC
Fans working none stop on Ayaneo Next Lite

**Comment by LukeShortCloud** [comment] 2024-10-30 21:18
Hopefully once we include basic power management, it will partially help reduce your fans from being at 100% speed.

Related: https://github.com/playtron-os/playtron-os/issues/160

How are the fan speeds on other Linux distributions? I've found my AYANEO 2S to generally be hotter than other devices I own due to how it was designed.

**Comment by LukeShortCloud** [comment] 2024-11-27 22:15
@Ferikash Are the fan speeds any better with Alpha 2?

You can update the OS by going to: Settings > General > Software Update

**Comment by LukeShortCloud** [comment] 2024-12-16 06:14
While not in-game, the fans should no longer be at 100%. When playing a game, I suspect they will go back to 100%. Alpha 2 is our first step at optimizing heat and performance. We'll have even more improvements in the future, too.

Closing as resolved.

**Closed by LukeShortCloud** 2024-12-16 06:14 UTC
Labels: bug
